export enum SagaState {
  ORDER_CREATED = 'ORDER_CREATED',
  INVENTORY_RESERVED = 'INVENTORY_RESERVED',
  PAYMENT_PROCESSED = 'PAYMENT_PROCESSED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  COMPENSATING = 'COMPENSATING',
  COMPENSATED = 'COMPENSATED',
}
